
services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "4173:4173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
